#!/usr/bin/env ksh

gfortran -O3 -Wall -c mbtypes.f90
gfortran -O3 -Wall -c mbmath.f90
gfortran -O3 -Wall -c mrgrnk.f90
gfortran -O3 -Wall -c setup.f90
gfortran -O3 -Wall -c image.f90
gfortran -O3 -Wall -c mandelbrot.f90
gfortran -O3 -Wall -o mb mrgrnk.o setup.o mbtypes.o mbmath.o image.o mandelbrot.o
